schema_version: 0.1
type: producer
identifier: libdv
title: libdv (*deprecated*)
version: 1
copyright: Meltytech, LLC
creator: Charles Yates
license: LGPLv2.1
language: en
tags:
  - Audio
  - Video
description: A libdv based decoder for video and audio.
parameters:
  - identifier: argument
    title: File
    type: string
    required: yes
    readonly: no
    widget: fileopen
    
  - identifier: quality
    title: Quality
    type: string
    description: One of "best," "fast" or anything else chooses medium.
    readonly: no
    mutable: yes
    widget: combo
    default: best
