schema_version: 0.1
type: producer
identifier: loader
title: Loader
version: 1
copyright: Meltytech, LLC
creator: Charles Yates
license: LGPLv2.1
language: en
tags:
  - Audio
  - Video
  - Hidden
description: >
  This producer has two roles:
  
  1. it handles the mappings of all file names to the other producers;
  
  2. it attaches normalising filters (rescale, resize and resample) to the 
  producers (when necessary).
  
  This producer simplifies many aspects of use. Essentially, it ensures that a 
  consumer will receive images and audio precisely as they request them. 
parameters:
  - identifier: argument
    title: File/URL
    type: string
    description: The file for the producer to be based on.
    required: no
    readonly: no
    widget: fileopen
