schema_version: 0.1
type: producer
identifier: consumer
title: Consumer as Producer
version: 2
copyright: Meltytech, LLC
creator: Dan Dennedy
license: LGPLv2.1
language: en
tags:
  - Audio
  - Video
parameters:
  - identifier: argument
    title: File/URL
    type: string
    description: A file name, URL, or producer name.
    required: yes

  - identifier: profile
    title: Profile
    type: string
    description: >
      The name of a MLT profile with which to load the resource. This defaults
      to the composition's profile, but could be overridden by the profile
      in MLT XML. Also, the value "auto" triggers profile detection.

  - identifier: autoprofile
    title: Auto-profile
    type: integer
    description: Generate a new, custom profile from the encapsulated resource.
    minimum: 0
    maximum: 1
    default: 0

  - identifier: producer.*
    title: Producer properties
    description: A property and its value to apply to the encapsulated producer.
    type: properties
    mutable: yes

  - identifier: consumer.*
    title: Consumer properties
    description: A property and its value to apply to the encapsulated consumer.
    type: properties
    mutable: yes
